const currencyMap = new Map([
	['0X0', '0X0'],
	['ABT', 'ABT'],
	['ACH', 'ACH'],
	['ACS', 'ACS'],
	['ADA', 'Cardano'],
	['AED', 'United Arab Emirates Dirham'],
	['AFN', 'Afghan Afghani'],
	['AKT', 'AKT'],
	['ALL', 'Albanian Lek'],
	['ALT', 'ALT'],
	['AMD', 'Armenian Dram'],
	['AMP', 'AMP'],
	['ANG', 'Netherlands Antillean Guilder'],
	['ANT', 'ANT'],
	['AOA', 'Angolan Kwanza'],
	['APE', 'APE'],
	['APL', 'APL'],
	['APT', 'APT'],
	['ARB', 'ARB'],
	['ARK', 'ARK'],
	['ARS', 'Argentine Peso'],
	['ASM', 'ASM'],
	['AST', 'AST'],
	['ATA', 'ATA'],
	['ATS', 'Austrian Schilling'],
	['AUD', 'Australian Dollar'],
	['AVT', 'AVT'],
	['AWG', 'Aruban Florin'],
	['AXL', 'AXL'],
	['AXS', 'AXS'],
	['AZM', 'Azerbaijani Manat (Old)'],
	['AZN', 'Azerbaijani Manat'],
	['BAL', 'BAL'],
	['BAM', 'Bosnia-Herzegovina Convertible Mark'],
	['BAT', 'BAT'],
	['BBD', 'Barbadian Dollar'],
	['BCH', 'Bitcoin Cash'],
	['BDT', 'Bangladeshi Taka'],
	['BDX', 'BDX'],
	['BEF', 'Belgian Franc'],
	['BGB', 'BGB'],
	['BGN', 'Bulgarian Lev'],
	['BHD', 'Bahraini Dinar'],
	['BIF', 'Burundian Franc'],
	['BIT', 'BIT'],
	['BLD', 'BLD'],
	['BLZ', 'BLZ'],
	['BMD', 'Bermudian Dollar'],
	['BNB', 'BNB'],
	['BND', 'Brunei Dollar'],
	['BNT', 'BNT'],
	['BOB', 'Bolivian Boliviano'],
	['BRL', 'Brazilian Real'],
	['BSD', 'Bahamian Dollar'],
	['BSV', 'Bitcoin SV'],
	['BSW', 'BSW'],
	['BTC', 'Bitcoin'],
	['BTG', 'Bitcoin Gold'],
	['BTN', 'Bhutanese Ngultrum'],
	['BTT', 'BTT'],
	['BWP', 'Botswana Pula'],
	['BYN', 'Belarusian Ruble'],
	['BYR', 'Belarusian Ruble (Old)'],
	['BZD', 'Belize Dollar'],
	['C98', 'C98'],
	['CAD', 'Canadian Dollar'],
	['CDF', 'Congolese Franc'],
	['CDT', 'CDT'],
	['CFG', 'CFG'],
	['CFX', 'CFX'],
	['CHF', 'Swiss Franc'],
	['CHR', 'CHR'],
	['CHZ', 'CHZ'],
	['CKB', 'CKB'],
	['CLP', 'Chilean Peso'],
	['CLV', 'CLV'],
	['CNH', 'Chinese Yuan (Offshore)'],
	['CNY', 'Chinese Yuan'],
	['COP', 'Colombian Peso'],
	['CQT', 'CQT'],
	['CRC', 'Costa Rican Colón'],
	['CRO', 'CRO'],
	['CRV', 'CRV'],
	['CTC', 'CTC'],
	['CTX', 'CTX'],
	['CUC', 'Cuban Convertible Peso'],
	['CUP', 'Cuban Peso'],
	['CVC', 'CVC'],
	['CVE', 'Cape Verdean Escudo'],
	['CVX', 'CVX'],
	['CYP', 'Cypriot Pound'],
	['CZK', 'Czech Koruna'],
	['DAG', 'DAG'],
	['DAI', 'DAI'],
	['DAO', 'DAO'],
	['DAR', 'DAR'],
	['DCR', 'Decred'],
	['DDX', 'DDX'],
	['DEM', 'German Mark'],
	['DFI', 'DFI'],
	['DIA', 'DIA'],
	['DJF', 'Djiboutian Franc'],
	['DKK', 'Danish Krone'],
	['DNT', 'DNT'],
	['DOP', 'Dominican Peso'],
	['DOT', 'DOT'],
	['DYM', 'DYM'],
	['DYP', 'DYP'],
	['DZD', 'Algerian Dinar'],
	['EDU', 'EDU'],
	['EEK', 'Estonian Kroon'],
	['EGP', 'Egyptian Pound'],
	['ELA', 'ELA'],
	['ELF', 'ELF'],
	['ELG', 'ELG'],
	['ENJ', 'ENJ'],
	['ENS', 'ENS'],
	['EOS', 'EOS'],
	['ERN', 'Eritrean Nakfa'],
	['ESP', 'Spanish Peseta'],
	['ETB', 'Ethiopian Birr'],
	['ETC', 'Ethereum Classic'],
	['ETH', 'Ethereum'],
	['EUR', 'Euro'],
	['FEI', 'FEI'],
	['FET', 'FET'],
	['FIL', 'FIL'],
	['FIM', 'Finnish Markka'],
	['FIS', 'FIS'],
	['FJD', 'Fijian Dollar'],
	['FKP', 'Falkland Islands Pound'],
	['FLR', 'FLR'],
	['FOK', 'FOK'],
	['FOX', 'FOX'],
	['FRF', 'French Franc'],
	['FTM', 'FTM'],
	['FTN', 'FTN'],
	['FTT', 'FTT'],
	['FXS', 'FXS'],
	['GAJ', 'GAJ'],
	['GAL', 'GAL'],
	['GAS', 'GAS'],
	['GBP', 'British Pound'],
	['GEL', 'Georgian Lari'],
	['GFI', 'GFI'],
	['GGP', 'GGP'],
	['GHC', 'Ghanaian Cedi (Old)'],
	['GHS', 'Ghanaian Cedi'],
	['GIP', 'Gibraltar Pound'],
	['GLM', 'GLM'],
	['GMD', 'Gambian Dalasi'],
	['GMT', 'GMT'],
	['GMX', 'GMX'],
	['GNF', 'Guinean Franc'],
	['GNO', 'GNO'],
	['GNS', 'GNS'],
	['GNT', 'GNT'],
	['GRD', 'Greek Drachma'],
	['GRT', 'GRT'],
	['GST', 'GST'],
	['GTC', 'GTC'],
	['GTQ', 'Guatemalan Quetzal'],
	['GXC', 'GXC'],
	['GYD', 'Guyanese Dollar'],
	['HFT', 'HFT'],
	['HKD', 'Hong Kong Dollar'],
	['HNL', 'Honduran Lempira'],
	['HNT', 'HNT'],
	['HOT', 'HOT'],
	['HRK', 'Croatian Kuna'],
	['HTG', 'Haitian Gourde'],
	['HUF', 'Hungarian Forint'],
	['ICP', 'ICP'],
	['ICX', 'ICX'],
	['IDR', 'Indonesian Rupiah'],
	['IEP', 'Irish Pound'],
	['ILS', 'Israeli New Shekel'],
	['ILV', 'ILV'],
	['IMP', 'IMP'],
	['IMX', 'IMX'],
	['INJ', 'INJ'],
	['INR', 'Indian Rupee'],
	['INV', 'INV'],
	['IQD', 'Iraqi Dinar'],
	['IRR', 'Iranian Rial'],
	['ISK', 'Icelandic Króna'],
	['ITL', 'Italian Lira'],
	['JEP', 'JEP'],
	['JMD', 'Jamaican Dollar'],
	['JOD', 'Jordanian Dinar'],
	['JOE', 'JOE'],
	['JPY', 'Japanese Yen'],
	['JST', 'JST'],
	['JTO', 'JTO'],
	['JUP', 'JUP'],
	['KAS', 'KAS'],
	['KCS', 'KCS'],
	['KDA', 'KDA'],
	['KES', 'Kenyan Shilling'],
	['KGS', 'Kyrgyzstani Som'],
	['KHR', 'Cambodian Riel'],
	['KID', 'KID'],
	['KMF', 'Comorian Franc'],
	['KNC', 'KNC'],
	['KPW', 'North Korean Won'],
	['KRL', 'KRL'],
	['KRW', 'South Korean Won'],
	['KSM', 'KSM'],
	['KUB', 'KUB'],
	['KWD', 'Kuwaiti Dinar'],
	['KYD', 'Cayman Islands Dollar'],
	['KZT', 'Kazakhstani Tenge'],
	['LAK', 'Lao Kip'],
	['LBP', 'Lebanese Pound'],
	['LCX', 'LCX'],
	['LDO', 'LDO'],
	['LEO', 'LEO'],
	['LIT', 'LIT'],
	['LKR', 'Sri Lankan Rupee'],
	['LPT', 'LPT'],
	['LRC', 'LRC'],
	['LRD', 'Liberian Dollar'],
	['LSK', 'LSK'],
	['LSL', 'Lesotho Loti'],
	['LTC', 'Litecoin'],
	['LTL', 'Lithuanian Litas'],
	['LUF', 'Luxembourg Franc'],
	['LVL', 'Latvian Lats'],
	['LYD', 'Libyan Dinar'],
	['LYX', 'LYX'],
	['MAD', 'Moroccan Dirham'],
	['MAV', 'MAV'],
	['MBX', 'MBX'],
	['MDL', 'Moldovan Leu'],
	['MDT', 'MDT'],
	['MGA', 'Malagasy Ariary'],
	['MGF', 'Malagasy Franc'],
	['MIR', 'MIR'],
	['MKD', 'Macedonian Denar'],
	['MKR', 'MKR'],
	['MLN', 'MLN'],
	['MMK', 'Myanmar Kyat'],
	['MNT', 'Mongolian Tögrög'],
	['MOG', 'MOG'],
	['MOP', 'Macanese Pataca'],
	['MPL', 'MPL'],
	['MRO', 'Mauritanian Ouguiya (Old)'],
	['MRU', 'Mauritanian Ouguiya'],
	['MTL', 'Maltese Lira'],
	['MUR', 'Mauritian Rupee'],
	['MVR', 'Maldivian Rufiyaa'],
	['MWK', 'Malawian Kwacha'],
	['MXC', 'MXC'],
	['MXN', 'Mexican Peso'],
	['MXV', 'MXV'],
	['MYR', 'Malaysian Ringgit'],
	['MZM', 'MZM'],
	['MZN', 'Mozambican Metical'],
	['NAD', 'Namibian Dollar'],
	['NCT', 'NCT'],
	['NEO', 'NEO'],
	['NFT', 'NFT'],
	['NGN', 'Nigerian Naira'],
	['NIO', 'Nicaraguan Córdoba'],
	['NKN', 'NKN'],
	['NLG', 'Dutch Guilder'],
	['NMR', 'NMR'],
	['NOK', 'Norwegian Krone'],
	['NOS', 'NOS'],
	['NPR', 'Nepalese Rupee'],
	['NXM', 'NXM'],
	['NZD', 'New Zealand Dollar'],
	['OAS', 'OAS'],
	['OGN', 'OGN'],
	['OHM', 'OHM'],
	['OKB', 'OKB'],
	['OKT', 'OKT'],
	['OMG', 'OMG'],
	['OMI', 'OMI'],
	['OMR', 'Omani Rial'],
	['ONE', 'ONE'],
	['ONT', 'ONT'],
	['ORN', 'ORN'],
	['OXT', 'OXT'],
	['PAB', 'Panamanian Balboa'],
	['PAX', 'PAX'],
	['PEN', 'Peruvian Sol'],
	['PGK', 'Papua New Guinean Kina'],
	['PHP', 'Philippine Peso'],
	['PKR', 'Pakistani Rupee'],
	['PLA', 'PLA'],
	['PLN', 'Polish Złoty'],
	['PLU', 'PLU'],
	['PNG', 'PNG'],
	['PRO', 'PRO'],
	['PRQ', 'PRQ'],
	['PTE', 'Portuguese Escudo'],
	['PYG', 'Paraguayan Guaraní'],
	['PYR', 'PYR'],
	['QAR', 'Qatari Riyal'],
	['QNT', 'QNT'],
	['QSP', 'QSP'],
	['RAD', 'RAD'],
	['RAI', 'RAI'],
	['RAY', 'RAY'],
	['RBN', 'RBN'],
	['REN', 'REN'],
	['REP', 'REP'],
	['REQ', 'REQ'],
	['RGT', 'RGT'],
	['RIF', 'RIF'],
	['RLB', 'RLB'],
	['RLC', 'RLC'],
	['RLY', 'RLY'],
	['ROL', 'Romanian Leu (Old)'],
	['RON', 'Romanian Leu'],
	['RPL', 'RPL'],
	['RSD', 'Serbian Dinar'],
	['RUB', 'Russian Ruble'],
	['RVN', 'RVN'],
	['RWF', 'Rwandan Franc'],
	['SAR', 'Saudi Riyal'],
	['SBD', 'Solomon Islands Dollar'],
	['SCR', 'Seychellois Rupee'],
	['SDD', 'Sudanese Dinar'],
	['SDG', 'Sudanese Pound'],
	['SEI', 'SEI'],
	['SEK', 'Swedish Krona'],
	['SFP', 'SFP'],
	['SGB', 'SGB'],
	['SGD', 'Singapore Dollar'],
	['SHP', 'Saint Helena Pound'],
	['SIT', 'Slovenian Tolar'],
	['SKK', 'Slovak Koruna'],
	['SKL', 'SKL'],
	['SLE', 'SLE'],
	['SLL', 'Sierra Leonean Leone'],
	['SLP', 'SLP'],
	['SNT', 'SNT'],
	['SNX', 'SNX'],
	['SOL', 'SOL'],
	['SOS', 'Somali Shilling'],
	['SPA', 'SPA'],
	['SPL', 'SPL'],
	['SRD', 'Surinamese Dollar'],
	['SRG', 'SRG'],
	['SSP', 'South Sudanese Pound'],
	['SSV', 'SSV'],
	['STD', 'São Tomé and Príncipe Dobra (Old)'],
	['STG', 'STG'],
	['STN', 'São Tomé and Príncipe Dobra'],
	['STX', 'STX'],
	['SUI', 'SUI'],
	['SVC', 'Salvadoran Colón'],
	['SXP', 'SXP'],
	['SYN', 'SYN'],
	['SYP', 'Syrian Pound'],
	['SZL', 'Eswatini Lilangeni'],
	['TAO', 'TAO'],
	['TET', 'TET'],
	['THB', 'Thai Baht'],
	['TIA', 'TIA'],
	['TJS', 'Tajikistani Somoni'],
	['TKX', 'TKX'],
	['TMM', 'TMM'],
	['TMT', 'TMT'],
	['TND', 'Tunisian Dinar'],
	['TON', 'TON'],
	['TOP', 'Tongan Paʻanga'],
	['TOR', 'TOR'],
	['TRB', 'TRB'],
	['TRL', 'TRL'],
	['TRU', 'TRU'],
	['TRX', 'TRX'],
	['TRY', 'Turkish Lira'],
	['TTD', 'Trinidad and Tobago Dollar'],
	['TTT', 'TTT'],
	['TVD', 'TVD'],
	['TVK', 'TVK'],
	['TWD', 'New Taiwan Dollar'],
	['TWT', 'TWT'],
	['TZS', 'Tanzanian Shilling'],
	['UAH', 'Ukrainian Hryvnia'],
	['UGX', 'Ugandan Shilling'],
	['UMA', 'UMA'],
	['UNI', 'UNI'],
	['UOS', 'UOS'],
	['UPI', 'UPI'],
	['UQC', 'UQC'],
	['USD', 'United States Dollar'],
	['UST', 'UST'],
	['UYU', 'Uruguayan Peso'],
	['UZS', 'Uzbekistani Som'],
	['VAL', 'VAL'],
	['VEB', 'VEB'],
	['VED', 'VED'],
	['VEF', 'VEF'],
	['VES', 'VES'],
	['VET', 'VET'],
	['VGX', 'VGX'],
	['VND', 'Vietnamese Đồng'],
	['VUV', 'Vanuatu Vatu'],
	['WBT', 'WBT'],
	['WIF', 'WIF'],
	['WLD', 'WLD'],
	['WOO', 'WOO'],
	['WST', 'Samoan Tala'],
	['XAF', 'Central African CFA Franc'],
	['XAG', 'Silver Ounce'],
	['XAI', 'XAI'],
	['XAU', 'Gold Ounce'],
	['XBT', 'Bitcoin'],
	['XCD', 'East Caribbean Dollar'],
	['XCH', 'XCH'],
	['XCN', 'XCN'],
	['XDC', 'XDC'],
	['XDR', 'Special Drawing Rights'],
	['XEC', 'XEC'],
	['XEM', 'XEM'],
	['XLM', 'Stellar'],
	['XMR', 'Monero'],
	['XOF', 'West African CFA Franc'],
	['XPD', 'Palladium Ounce'],
	['XPF', 'CFP Franc'],
	['XPT', 'Platinum Ounce'],
	['XRD', 'XRD'],
	['XRP', 'Ripple'],
	['XTZ', 'Tezos'],
	['XVS', 'XVS'],
	['XYO', 'XYO'],
	['YER', 'Yemeni Rial'],
	['YFI', 'YFI'],
	['ZAR', 'South African Rand'],
	['ZEC', 'Zcash'],
	['ZEN', 'ZEN'],
	['ZIL', 'Zilliqa'],
	['ZMK', 'Zambian Kwacha (Old)'],
	['ZMW', 'Zambian Kwacha'],
	['ZRX', 'ZRX'],
	['ZWD', 'Zimbabwean Dollar (Old)'],
	['ZWL', 'Zimbabwean Dollar']
]);

/**
 * Returns the currency name from the currency code
 * @param {string} code
 * @returns {string | undefined}
 */
export function toCurrencyName(code) {
	const codeUpper = code.toUpperCase();
	return currencyMap.get(codeUpper);
}

/**
 * Returns the currency code from the currency name
 * @param {string} name
 * @returns {string | undefined}
 */
export function toCurrencyCode(name) {
	for (const [key, value] of currencyMap.entries()) {
		if (value.toLowerCase() === name.toLowerCase()) return key;
	}
	return undefined;
}

/**
 * Returns the currency code if the input is a currency code or name
 * @param {string} input
 * @returns {string | undefined}
 */
export function getCurrencyCode(input) {
	const inputUpper = input.toUpperCase();
	return currencyMap.has(inputUpper) ? inputUpper : toCurrencyCode(input);
}
